### ISSUE TITLE
[Bug]: OCP\AppFramework\Db\Mapper removed in NC26

### ISSUE THREAD

**Issue by tacruc** [nextcloud/maps#948]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Maps app **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

OCP\AppFramework\Db\Mapper removed in NC26

### Steps to reproduce

1. Upgrade to NC26

### Expected behavior

Fix don't use OCP\AppFramework\DB\Mapper
Possible alternatives:

- Directly search for images via DAV request
- Use different DB connection

### Installation method

None

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install of the server?

None

### Is this bug present after an update or on a fresh install of the app?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
- maps
```

**Comment by tacruc** [comment]
Fixed by #950

**Comment by skjerns** [comment]
After upgrading to 26.0.0, I get the following error now, related to this deprecation

Any idea how to fix this when I only have file system access (no terminal)?

```
{"reqId":"i3wx2nd6OG9ODL6BZoMK","level":3,"time":"2023-04-07T15:13:35+00:00","remoteAddr":"2a02:8071:2c81:5b60:7654:60c4:5c09:952f","user":"root","app":"index","method":"GET","url":"/index.php/apps/theming/image/logo?v=41","message":"Class \"OCP\\AppFramework\\Db\\Mapper\" not found","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36","version":"26.0.0.11","exception":{"Exception":"Error","Message":"Class \"OCP\\AppFramework\\Db\\Mapper\" not found","Code":0,"Trace":[{"file":"/var/www/vhosts/hosting154271.a2ed6.netcup.net/cloud.xxx.de/lib/composer/composer/ClassLoader.php","line":578,"function":"include"},{"file":"/var/www/vhosts/hosting154271.a2ed6.netcup.net/cloud.xxx.de/lib/composer/composer/ClassLoader.php","line":432,"function":"Composer\\Autoload\\{closure}","class":"Composer\\Autoload\\ClassLoader","type":"::","args":["*** sensitive parameters replaced ***"]},{"function":"loadClass","class":"Composer\\Autoload\\ClassLoader","type":"->","args":["OCA\\Richdocuments\\Db\\WopiMapper"]},{"file":"/var/www/vhosts/hosting154271.a2ed6.netcup.net/cloud.xxx.de/lib/private/AppFramework/Utility/SimpleContainer.php","line":122,"function":"__construct","class":"ReflectionClass","type":"->","args":["OCA\\Richdocuments\\Db\\WopiMapper"]},{"file":"/var/www/vhosts/hosting154271.a2ed6.netcup.net/cloud.xxx.de/lib/private/AppFramework/Utility/SimpleContainer.php","line":142,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Richdocuments\\Db\\WopiMapper"]},{"file":"/var/www/vhosts/hosting154271.a2ed6.netcup.net/cloud.xxx.de/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":493,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Richdocuments\\Db\\WopiMapper"]},{"file":"/var/www/vhosts/hosting154271.a2ed6.netcup.net/cloud.xxx.de/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":465,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Richdocuments\\Db\\WopiMapper"]},{"file":"/var/www/vhosts/hosting154271.a2ed6.netcup.net/cloud.xxx.de/lib/private/AppFramework/Utility/SimpleContainer.php","line":97,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Richdocuments\\Db\\WopiMapper",true]},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/vhosts/hosting154271.a2ed6.netcup.net/cloud.xxx.de/lib/private/AppFramework/Utility/SimpleContainer.php","line":116,"function":"array_map","args":[["Closure"],[["ReflectionParameter","rootFolder"],["ReflectionParameter","shareManager"],["ReflectionParameter","urlGenerator"],["ReflectionParameter","wopiParser"],["ReflectionParameter","capabilitiesService"],["ReflectionParameter","UserId"],"*** sensitive parameters replaced ***",["ReflectionParameter","trans"],["ReflectionParameter","helper"],["ReflectionParameter","permissionManager"]]]},{"file":"/var/www/vhosts/hosting154271.a2ed6.netcup.net/cloud.xxx.de/lib/private/AppFramework/Utility/SimpleContainer.php","line":124,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[["ReflectionClass","OCA\\Richdocuments\\TokenManager"]]},{"file":"/var/www/vhosts/hosting154271.a2ed6.netcup.net/cloud.xxx.de/lib/private/AppFramework/Utility/SimpleContainer.php","line":142,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Richdocuments\\TokenManager"]},{"file":"/var/www/vhosts/hosting154271.a2ed6.netcup.net/cloud.xxx.de/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":493,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Richdocuments\\TokenManager"]},{"file":"/var/www/vhosts/hosting154271.a2ed6.netcup.net/cloud.xxx.de/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":465,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Richdocuments\\TokenManager"]},{"file":"/var/www/vhosts/hosting154271.a2ed6.netcup.net/cloud.xxx.de/lib/private/AppFramework/Utility/SimpleContainer.php","line":97,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Richdocuments\\TokenManager",true]},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/vhosts/hosting154271.a2ed6.netcup.net/cloud.xxx.de/lib/private/AppFramework/Utility/SimpleContainer.php","line":116,"function":"array_map","args":[["Closure"],[["ReflectionParameter","cacheFactory"],["ReflectionParameter","clientService"],["ReflectionParameter","logger"],"*** sensitive parameters replaced ***",["ReflectionParameter","appConfig"],["ReflectionParameter","request"],["ReflectionParameter","urlGenerator"]]]},{"file":"/var/www/vhosts/hosting154271.a2ed6.netcup.net/cloud.xxx.de/lib/private/AppFramework/Utility/SimpleContainer.php","line":124,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[["ReflectionClass","OCA\\Richdocuments\\Service\\FederationService"]]},{"file":"/var/www/vhosts/hosting154271.a2ed6.netcup.net/cloud.xxx.de/lib/private/AppFramework/Utility/SimpleContainer.php","line":142,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Richdocuments\\Service\\FederationService"]},{"file":"/var/www/vhosts/hosting154271.a2ed6.netcup.net/cloud.xxx.de/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":493,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Richdocuments\\Service\\FederationService"]},{"file":"/var/www/vhosts/hosting154271.a2ed6.netcup.net/cloud.xxx.de/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":465,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Richdocuments\\Service\\FederationService"]},{"file":"/var/www/vhosts/hosting154271.a2ed6.netcup.net/cloud.xxx.de/lib/private/AppFramework/Utility/SimpleContainer.php","line":97,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Richdocuments\\Service\\FederationService",true]},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/vhosts/hosting154271.a2ed6.netcup.net/cloud.xxx.de/lib/private/AppFramework/Utility/SimpleContainer.php","line":116,"function":"array_map","args":[["Closure"],[["ReflectionParameter","request"],["ReflectionParameter","config"],["ReflectionParameter","appManager"],"*** sensitive parameters replaced ***",["ReflectionParameter","globalScaleConfig"]]]},{"file":"/var/www/vhosts/hosting154271.a2ed6.netcup.net/cloud.xxx.de/lib/private/AppFramework/Utility/SimpleContainer.php","line":124,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[["ReflectionClass","OCA\\Richdocuments\\Listener\\CSPListener"]]},{"file":"/var/www/vhosts/hosting154271.a2ed6.netcup.net/cloud.xxx.de/lib/private/AppFramework/Utility/SimpleContainer.php","line":142,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Richdocuments\\Listener\\CSPListener"]},{"file":"/var/www/vhosts/hosting154271.a2ed6.netcup.net/cloud.xxx.de/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":493,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Richdocuments\\Listener\\CSPListener"]},{"file":"/var/www/vhosts/hosting154271.a2ed6.netcup.net/cloud.xxx.de/lib/private/ServerContainer.php","line":155,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Richdocuments\\Listener\\CSPListener"]},{"file":"/var/www/vhosts/hosting154271.a2ed6.netcup.net/cloud.xxx.de/lib/private/EventDispatcher/ServiceEventListener.php","line":70,"function":"query","class":"OC\\ServerContainer","type":"->","args":["OCA\\Richdocuments\\Listener\\CSPListener"]},{"file":"/var/www/vhosts/hosting154271.a2ed6.netcup.net/cloud.xxx.de/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":251,"function":"__invoke","class":"OC\\EventDispatcher\\ServiceEventListener","type":"->","args":[["OCP\\Security\\CSP\\AddContentSecurityPolicyEvent"],"OCP\\Security\\CSP\\AddContentSecurityPolicyEvent",["Symfony\\Component\\EventDispatcher\\EventDispatcher"]]},{"file":"/var/www/vhosts/hosting154271.a2ed6.netcup.net/cloud.xxx.de/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[[["Closure"],["Closure"]],"OCP\\Security\\CSP\\AddContentSecurityPolicyEvent",["OCP\\Security\\CSP\\AddContentSecurityPolicyEvent"]]},{"file":"/var/www/vhosts/hosting154271.a2ed6.netcup.net/cloud.xxx.de/lib/private/EventDispatcher/EventDispatcher.php","line":87,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[["OCP\\Security\\CSP\\AddContentSecurityPolicyEvent"],"OCP\\Security\\CSP\\AddContentSecurityPolicyEvent"]},{"file":"/var/www/vhosts/hosting154271.a2ed6.netcup.net/cloud.xxx.de/lib/private/EventDispatcher/EventDispatcher.php","line":99,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->","args":["OCP\\Security\\CSP\\AddContentSecurityPolicyEvent",["OCP\\Security\\CSP\\AddContentSecurityPolicyEvent"]]},{"file":"/var/www/vhosts/hosting154271.a2ed6.netcup.net/cloud.xxx.de/lib/private/Security/CSP/ContentSecurityPolicyManager.php","line":60,"function":"dispatchTyped","class":"OC\\EventDispatcher\\EventDispatcher","type":"->","args":[["OCP\\Security\\CSP\\AddContentSecurityPolicyEvent"]]},{"file":"/var/www/vhosts/hosting154271.a2ed6.netcup.net/cloud.xxx.de/lib/private/AppFramework/Middleware/Security/CSPMiddleware.php","line":70,"function":"getDefaultPolicy","class":"OC\\Security\\CSP\\ContentSecurityPolicyManager","type":"->","args":[]},{"file":"/var/www/vhosts/hosting154271.a2ed6.netcup.net/cloud.xxx.de/lib/private/AppFramework/Middleware/MiddlewareDispatcher.php","line":142,"function":"afterController","class":"OC\\AppFramework\\Middleware\\Security\\CSPMiddleware","type":"->","args":[["OCA\\Theming\\Controller\\ThemingController"],"getImage",["OCP\\AppFramework\\Http\\FileDisplayResponse"]]},{"file":"/var/www/vhosts/hosting154271.a2ed6.netcup.net/cloud.xxx.de/lib/private/AppFramework/Http/Dispatcher.php","line":175,"function":"afterController","class":"OC\\AppFramework\\Middleware\\MiddlewareDispatcher","type":"->","args":[["OCA\\Theming\\Controller\\ThemingController"],"getImage",["OCP\\AppFramework\\Http\\FileDisplayResponse"]]},{"file":"/var/www/vhosts/hosting154271.a2ed6.netcup.net/cloud.xxx.de/lib/private/AppFramework/App.php","line":183,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Theming\\Controller\\ThemingController"],"getImage"]},{"file":"/var/www/vhosts/hosting154271.a2ed6.netcup.net/cloud.xxx.de/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Theming\\Controller\\ThemingController","getImage",["OC\\AppFramework\\DependencyInjection\\DIContainer"],["logo","theming.Theming.getImage"]]},{"file":"/var/www/vhosts/hosting154271.a2ed6.netcup.net/cloud.xxx.de/lib/base.php","line":1055,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/theming/image/logo"]},{"file":"/var/www/vhosts/hosting154271.a2ed6.netcup.net/cloud.xxx.de/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/vhosts/hosting154271.a2ed6.netcup.net/cloud.xxx.de/apps/richdocuments/lib/Db/WopiMapper.php","Line":35,"CustomMessage":"--"}}
```

**Comment by skjerns** [comment]
I fixed the issue by deleting the `/apps/richdocuments/` folder and reinstalling the app

**Comment by mcwimh** [comment]
Still have the same problem, removed richdocuments, richtext, rich-anything, Deck. Nothing helps. Even migrated from raspberry pi to imac with ubuntu. No change. See the subject is closed, but does someone know if its still going on anywhere?

**Comment by yslemmo** [comment]
When I enabled the richdocuments plugin, it prompted a server error in the NC Web, and after I deleted the `/apps/richdocuments/` folder, it launched normally!
